name: Format C++

on:
  push:
    branches: [ devel, release/**, format-cpp ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ devel, release/** ]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install fprime-tools
      run: |
        pip install fprime-tools
    - name: Check formatting
      env:
        FOLDERS_LIST: "config"
      run: ./.github/actions/check-cpp-format.sh